app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['auth', 'usuario.verificar']], function(){
  Route::get('/home', 'IndexController@index');
  Route::get('/', 'IndexController@index');
  Route::resource('usuarios', 'UsersController');
  // mensajes de algun usuario
  Route::get('usuarios/mensajes/{id}', 'MessagesByUserController@show');
  Route::resource('edificios', 'BuildingsController');
  // items en algun edificio
  Route::get('edificios/items/{edificios}', 'BuildingsController@items');
  // eventos en algun edificio
  Route::get('edificios/eventos/{edificios}', 'BuildingsController@events');
  // mensajes de algun edificio
  Route::get('edificios/mensajes/{edificios}', 'BuildingsController@messages');
  // crear un movimiento relacionado con un edificio
  Route::get('edificios/movimientos/{edificios}/create', 'BuildingsController@movementsCreate');
  // movimientos de algun edificio (caja chica)
  Route::get('edificios/movimientos/{edificios}', 'BuildingsController@movements');
  // gestiones multifamiliares de algun edificio
  Route::get('edificios/gestiones/{edificios}', 'BuildingsController@gestions');
  // crea un miembro de gestion multifamiliar de algun edificio
  Route::get('edificios/gestiones/{edificios}/create', 'BuildingsController@gestionsCreate');
  Route::resource('apartamentos', 'ApartmentsController');
  // para crear multiples apartamentos al mismo tiempo.
  Route::get('apartamentos/crear-multiples/{edificios}', 'ApartmentsController@createMultiple');
  Route::post('apartamentos/storeMultiple/{edificios}', 'ApartmentsController@storeMultiple');
  Route::resource('mensajes', 'MessagesController');
  Route::resource('eventos', 'EventsController');
  Route::resource('items', 'ItemsController');
  Route::resource('movimientos', 'MovementsController');
  // GESTIONES
  // guardar nuevo
  Route::post('gestiones', 'GestionsController@store');
  // actualizar
  Route::get('gestiones/{usuarios}/{edificios}', 'GestionsController@edit');
  // guardar actualizaciones
  Route::patch('gestiones/{gestiones}', 'GestionsController@update');
  Route::delete('gestiones/{usuarios}/{edificios}', 'GestionsController@destroy');
});

// para asignar un usuario a un apartamento de un edifico
Route::group(['middleware' => 'usuario.verificado'], function(){
  // usuario por verificar
  Route::get('/por-verificar', 'IndexController@porVerificar');
  // para generar confirmaciones de usuario
  Route::get('/generar-confirmacion', 'ConfirmationsController@generateConfirm');
  Route::get('/confirmar/{string}', 'ConfirmationsController@confirm');
});

// para asignar un usuario a un apartamento de un edifico
Route::group(['middleware' => ['auth', 'usuario.verificar', 'usuario.edificio'], 'prefix' => 'asignar-edificio', 'as' => 'asignarApartamento'], function(){
  Route::get('/', 'AssignApartmentsController@index');
  Route::get('/{id}/create', 'AssignApartmentsController@create');
  // asignar apartamentos a un usuario existente
  Route::get('/{id}/create-habitante', 'AssignApartmentsController@createFromUserId');
  Route::post('/{id}/create-habitante', 'AssignApartmentsController@storeFromUserId');
  // esta es la version mamarracha
  Route::post('/{id}', 'AssignApartmentsController@store');
});

// pisos en algun edificio (para ajax de pisos)
Route::get('edificios/floors/{edificios}', 'BuildingsController@floors');
// apartamentos en algun edificio (para ajax)
Route::get('edificios/apartments/{edificios}', 'BuildingsController@apartments');
// para ajax de direcciones
Route::get('/estados', 'DirectionsController@states');
Route::get('/municipios/{id}', 'DirectionsController@towns');
Route::get('/municipio/{id}', 'DirectionsController@town');
Route::get('/parroquias/{id}', 'DirectionsController@parishes');
Route::get('/parroquia/{id}', 'DirectionsController@parish');
// para asignar habitante por medio de ajax
Route::get('/habitantes/{usuarios}/{apartamentos}',
  'AssignApartmentsController@storeFromIdentity');
Route::get('/habitantes-remover/{usuarios}/{apartamentos}',
  'AssignApartmentsController@removeFromIdentity');

Route::controllers([
  'auth' => 'Auth\AuthController',
  'password' => 'Auth\PasswordController',
]);

app/User.php
<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Profile;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

  use Authenticatable, CanResetPassword, SoftDeletes;

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'users';

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'username',
    'email',
    'password',
    'identity_card',
    'first_name',
    'middle_name',
    'first_surname',
    'last_surname',
    'sex_id',
    'profile_id',
    'birth_date',
    'phone',
    'aditional_phone'
  ];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = ['password', 'remember_token'];

  /**
   * El campo que utiliza SoftDeletes para hacer status = 0
   *
   * @var array
   */
  protected $dates = ['deleted_at'];

  public function scopeAdministradores($query)
  {
    $perfil = Profile::where('description', 'Administrador')->first();
    return $query->where('profile_id', $perfil->id);
  }

  /**
   * regresa los eventos paginados
   * @return object LengthAwarePaginator
   */
  public function getEventosPaginadosAttribute()
  {
    return $this->eventos()->paginate(5);
  }

  /**
   * regresa los eventos paginados
   * @return object LengthAwarePaginator
   */
  public function getMensajesPaginadosAttribute()
  {
    return $this->mensajes()->paginate(5);
  }

  /**
   * regresa los ultimos 3 mensajes relacionados con el edificio
   */
  public function getUltimosMensajesAttribute()
  {
    return $this->mensajes()->orderBy('updated_at', 'desc')->take(3)->get();
  }

  /**
   * la asociacion entre usuarios y perfiles en la base de datos
   * en donde los parametros son
   * ('el modelo', 'el pivote', 'su llave foranea en pivote')
   */
  public function perfil(){
    return $this->belongsTo('App\Profile', 'profile_id');
  }

  /**
   * un usuario puede tener muchos apartamentos
   * esto es una relacion NaM
   */
  public function apartamentos(){
    return $this->belongsToMany('App\Apartment');
  }

  /**
   * un usuario puede tener un sexo
   * esto es una relacion 1aN
   */
  public function sexo(){
    return $this->belongsTo('App\Sex');
  }

  /**
   * las propiedades (apartamentos) de un usuario
   * esto es una relacion 1aN
   * @return [type] [description]
   */
  public function propiedades(){
    return $this->hasMany('App\Apartment');
  }

  /**
   * un usuario tiene muchos mensajes y
   * un mensaje pertenece a un usuario
   */
  public function mensajes(){
    return $this->hasMany('App\Message');
  }

  /**
   * un usuario tiene muchos mensajes y
   * un mensaje pertenece a un usuario
   */
  public function eventos(){
    return $this->hasMany('App\Event');
  }

  /**
   * un usuario tiene muchos edificios (encargado) y
   * un edificio pertenece a un usuario
   */
  public function edificios(){
    return $this->hasMany('App\Building', 'user_id');
  }
  /**
   * la relacion de gestion multifamiliar
   */
  public function gestiones(){
    return $this->belongsToMany('App\Building');
  }

  /**
   * un usuario tiene muchas cuentas (titular) y
   * un cuenta pertenece a un usuario
   */
  public function cuentas(){
    return $this->hasMany('App\Account', 'user_id');
  }

  /**
   * un usuario tiene muchos movimientos (responsable)
   * y un movimiento pertenece a un usuario
   */
  public function movimientos(){
    return $this->hasMany('App\Movement', 'user_id');
  }

  /**
   * Un usuario tiene una sola confirmacion
   */
  public function confirmacion(){
    return $this->hasOne('App\UserConfirmation');
  }

  /**
   * debido a que no se todava implementar
   * laravel correctamente tengo que
   * hacer esta mamarrachada
   */
  public function insertarMensaje($request){
    $mensaje = new \App\Message($request->all());
    $mensaje->message_type_id = $request->input('types')[0];
    $mensaje->created_by = $this->id;
    $mensaje->updated_by = $this->id;
    return $mensaje;
  }

  public function esAdministrador()
  {
    if ($this->perfil->description === 'Administrador') return true;
    return false;
  }

  public function esJuntaCondominio()
  {
   if ($this->perfil->description === 'Junta de Condominio') return true;
    return false;
  }

  public function desactivado()
  {
   if ($this->perfil->description === 'Desactivado') return true;
    return false;
  }

  public function verificado()
  {
   if ($this->perfil->description !== 'Desactivado') return true;
    return false;
  }

  public function esUsuario()
  {
   if ($this->perfil->description === 'Usuario') return true;
    return false;
  }

  public function esAyudante()
  {
   if ($this->perfil->description === 'Ayudante') return true;
    return false;
  }

  public function sinEdificio()
  {
   if ($this->perfil->description === 'Sin Edificio') return true;
    return false;
  }

}

app/Http/Controllers/UsersController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Controllers\Controller;
use App\User;
use App\Sex;
use Auth;

use Illuminate\Http\Request;

class UsersController extends Controller {


  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
    $this->middleware('administrador.evento', ['except' => ['show']]);
  }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $usuarios = User::all();
    return view('users.index', compact('usuarios'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    $usuario = new User;
    $sexos = Sex::lists('description', 'id');

    return view('users.create', compact('usuario', 'sexos'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(UserRequest $request)
  {
    $usuario = new User($request->all());
    $usuario->save();
    flash('El usuario ha sido creado con exito.');
    return redirect()->action('IndexController@index');
    // return $usuario;
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $usuario = User::findOrFail($id);

    return view('users.show', compact('usuario'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $usuario = User::findOrFail($id);
    $sexos = Sex::lists('description', 'id');

    return view('users.edit', compact('usuario', 'sexos'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id, UserUpdateRequest $request)
  {
    $usuario = User::findOrFail($id);
    // actualiza el usuario
    $usuario->update($request->all());
    // mensaje de exito
    flash('El usuario ha sido actualizado con exito.');
    return redirect()->action('UsersController@index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    //
  }

}

resources/views/users/_form.blade.php
<div class="form-group">
  {!! Form::label('first_name', 'Primer Nombre:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('first_name', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('middle_name', 'Segundo Nombre:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('middle_name', null, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('first_surname', 'Primer Apellido:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('first_surname', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('last_surname', 'Segundo Apellido:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('last_surname', null, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('email', 'E-mail:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('identity_card', 'Cedula:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('identity_card', null, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('birth_date', 'Fecha de Nacimiento:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::input('date', 'birth_date', $usuario->birth_date, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('sex_id', 'Genero:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::select('sex_id', $sexos, $usuario->sex_id, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('phone', 'Telefono:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::input('tel', 'phone', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('aditional_phone', 'Telefono Adicional:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::input('tel', 'aditional_phone', null, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    {!! Form::submit($textoBotonSubmit, ['class' => 'form-control btn btn-primary']) !!}
  </div>
</div>

resources/views/users/create.blade.php
@extends('master')

@section('title')
  - Crear - Usuario
@stop

@section('contenido')
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">Crea un nuevo Usuario en el sistemaCONDOR</div>
          <div class="panel-body">
            @include('errors.lista')
            {!! Form::open(['action' => 'UsersController@store', 'class' => 'form-horizontal']) !!}
              @include('users._form', ['textoBotonSubmit' => 'Añadir nuevo Usario'])
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@stop

resources/views/users/edit.blade.php
@extends('master')

@section('title')
  - Actualizar - Usuario
@stop

@section('contenido')
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">Actualizar Usuario en el sistemaCONDOR</div>
          <div class="panel-body">
            @include('errors.lista')
            {!! Form::model($usuario, [
                'method' => 'PATCH',
                'action' => ['UsersController@update', $usuario->id],
                'class'  => 'form-horizontal'
                ]) !!}
              @include('users._form', ['textoBotonSubmit' => 'Actualizar Usuario'])
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@stop

resources/views/users/index.blade.php
@extends('master')

@section('title')
  - Usuarios en el sistema
@stop

@section('css')
  <link rel="stylesheet" type="text/css" href="{!! asset('vendor/css/bootstrap-table/bootstrap-table.css') !!}">
@stop

@section('contenido')
  <div class="container">
    <h1>Usuarios en el sistema</h1>
    @include('errors.lista')
    <hr/>
    <div class="row">
      <div class="col-sm-12">
        <table
          id="tabla"
          data-toggle="table"
          data-search="true"
          data-height="400"
          data-pagination="true"
          data-page-list="[10, 25, 50, 100]"
          data-show-toggle="true"
          data-show-columns="true"
          data-click-to-select="true"
          data-maintain-selected="true"
          data-sort-name="first_name"
          >
          <thead>
            <th data-field="first_name" data-sortable="true" data-switchable="false">
              Primer Nombre
            </th>
            <th data-field="first_surname" data-sortable="true" data-switchable="false">
              Primer Apellido
            </th>
            <th data-field="email" data-sortable="true" data-switchable="true">
              Correo Electronico
            </th>
            <th data-field="phone" data-sortable="true" data-switchable="true">
              Telefono
            </th>
          </thead>
          <tbody>
            @foreach ($usuarios as $usuario)
              <tr>
                <td>
                  {{ $usuario->first_name }}
                </td>
                <td>
                  {{ $usuario->first_surname }}
                </td>
                <td>
                  {{ $usuario->email }}
                </td>
                <td>
                  {{ $usuario->phone }}
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@stop

@section('js')
  <script src="{!! asset('vendor/js/bootstrap-table/bootstrap-table.js') !!}"></script>
  <script src="{!! asset('vendor/js/bootstrap-table/bootstrap-table-es-CR.js') !!}"></script>
@stop

resources/views/users/show.blade.php
@extends('master')

@section('title')
  - Perfil - Usuario
@stop

@section('contenido')
  <div class="container">
    <h1>
      {{ $usuario->first_name }}
      {{ $usuario->middle_name }},
      {{ $usuario->first_surname }}
      {{ $usuario->last_surname }}
      <small>
        ({{$usuario->username}})
      </small>
      @if (Auth::user()->id === $usuario->id)
        {!!link_to_action(
            'UsersController@edit',
            'Editar',
            $usuario->id,
            ['class' => 'btn btn-primary']) !!}
      @endif
    </h1>
    <p>
      Cedula de indentidad: {{ $usuario->identity_card }}
    </p>

    <h3>Informacion de contacto</h3>
    <p>
      {!! Html::mailto($usuario->email) !!}
      {{ $usuario->phone }}
      {{ $usuario->aditional_phone }}
    </p>
    <hr/>
    <section>
      @unless ($usuario->apartamentos()->get()->isEmpty())
        Perteneciente a
        @foreach ($usuario->apartamentos as $apartamento)
          <h4>
            {!!link_to_action(
                'BuildingsController@show',
                $apartamento->edificio->name,
                $apartamento->edificio->id) !!}
            <small>
              Piso
              {{ $apartamento->floor }}
              {!! link_to_action('ApartmentsController@show', 'Apartamento '.$apartamento->number, $apartamento->id) !!}
            </small>
          </h4>
        @endforeach
      @else
        @if (Auth::user()->perfil->description === 'Administrador' or Auth::user()->id === $usuario->id)
          {!! link_to_action('AssignApartmentsController@createFromUserId', 'Asignar Apartamento', $usuario->id, ['class' => 'btn btn-primary']) !!}
        @endif
      @endunless
    </section>
    <hr/>
    <section>
      Perfil
        <h4>
          {{ $usuario->perfil->description }}
        </h4>
    </section>
  </div>
  <div id="lista-12">
    <h3>
      Ultimos mensajes
      {!!link_to_action(
        'MessagesController@create',
        'Crear Nuevo', null,
        ['class' => 'btn btn-primary']) !!}
    </h3>
    @foreach ($usuario->ultimos_mensajes as $mensaje)
      <div class="modelo">
        <div class="detalles">
          <article>
            <header>
              <h4>
                @if (Auth::user()->id === $usuario->id)
                  {!!link_to_action(
                    'MessagesController@edit',
                    $mensaje->title,
                    $mensaje->id) !!}
                @else
                  {!!link_to_action(
                    'MessagesController@show',
                    $mensaje->title,
                    $mensaje->id) !!}
                @endif
              </h4>
            </header>
            <p class="body">
              {{ $mensaje->body }}
            </p>
            <footer>
              <p>
                <strong>
                  {!! $mensaje->tipo->description !!}.
                </strong>
                <i>
                  Ultima actualizacion
                  {!! Date::parse($mensaje->updated_at)->diffForHumans(); !!}.
                </i>
              </p>
            </footer>
          </article>
        </div>
      </div>
    @endforeach
  </div>
@stop