app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['auth', 'usuario.verificar']], function(){
  Route::get('/home', 'IndexController@index');
  Route::get('/', 'IndexController@index');
  Route::resource('usuarios', 'UsersController');
  // mensajes de algun usuario
  Route::get('usuarios/mensajes/{id}', 'MessagesByUserController@show');
  Route::resource('edificios', 'BuildingsController');
  // items en algun edificio
  Route::get('edificios/items/{edificios}', 'BuildingsController@items');
  // eventos en algun edificio
  Route::get('edificios/eventos/{edificios}', 'BuildingsController@events');
  // mensajes de algun edificio
  Route::get('edificios/mensajes/{edificios}', 'BuildingsController@messages');
  // crear un movimiento relacionado con un edificio
  Route::get('edificios/movimientos/{edificios}/create', 'BuildingsController@movementsCreate');
  // movimientos de algun edificio (caja chica)
  Route::get('edificios/movimientos/{edificios}', 'BuildingsController@movements');
  // gestiones multifamiliares de algun edificio
  Route::get('edificios/gestiones/{edificios}', 'BuildingsController@gestions');
  // crea un miembro de gestion multifamiliar de algun edificio
  Route::get('edificios/gestiones/{edificios}/create', 'BuildingsController@gestionsCreate');
  Route::resource('apartamentos', 'ApartmentsController');
  // para crear multiples apartamentos al mismo tiempo.
  Route::get('apartamentos/crear-multiples/{edificios}', 'ApartmentsController@createMultiple');
  Route::post('apartamentos/storeMultiple/{edificios}', 'ApartmentsController@storeMultiple');
  Route::resource('mensajes', 'MessagesController');
  Route::resource('eventos', 'EventsController');
  Route::resource('items', 'ItemsController');
  Route::resource('movimientos', 'MovementsController');
  // GESTIONES
  // guardar nuevo
  Route::post('gestiones', 'GestionsController@store');
  // actualizar
  Route::get('gestiones/{usuarios}/{edificios}', 'GestionsController@edit');
  // guardar actualizaciones
  Route::patch('gestiones/{gestiones}', 'GestionsController@update');
  Route::delete('gestiones/{usuarios}/{edificios}', 'GestionsController@destroy');
});

// para asignar un usuario a un apartamento de un edifico
Route::group(['middleware' => 'usuario.verificado'], function(){
  // usuario por verificar
  Route::get('/por-verificar', 'IndexController@porVerificar');
  // para generar confirmaciones de usuario
  Route::get('/generar-confirmacion', 'ConfirmationsController@generateConfirm');
  Route::get('/confirmar/{string}', 'ConfirmationsController@confirm');
});

// para asignar un usuario a un apartamento de un edifico
Route::group(['middleware' => ['auth', 'usuario.verificar', 'usuario.edificio'], 'prefix' => 'asignar-edificio', 'as' => 'asignarApartamento'], function(){
  Route::get('/', 'AssignApartmentsController@index');
  Route::get('/{id}/create', 'AssignApartmentsController@create');
  // asignar apartamentos a un usuario existente
  Route::get('/{id}/create-habitante', 'AssignApartmentsController@createFromUserId');
  Route::post('/{id}/create-habitante', 'AssignApartmentsController@storeFromUserId');
  // esta es la version mamarracha
  Route::post('/{id}', 'AssignApartmentsController@store');
});

// pisos en algun edificio (para ajax de pisos)
Route::get('edificios/floors/{edificios}', 'BuildingsController@floors');
// apartamentos en algun edificio (para ajax)
Route::get('edificios/apartments/{edificios}', 'BuildingsController@apartments');
// para ajax de direcciones
Route::get('/estados', 'DirectionsController@states');
Route::get('/municipios/{id}', 'DirectionsController@towns');
Route::get('/municipio/{id}', 'DirectionsController@town');
Route::get('/parroquias/{id}', 'DirectionsController@parishes');
Route::get('/parroquia/{id}', 'DirectionsController@parish');
// para asignar habitante por medio de ajax
Route::get('/habitantes/{usuarios}/{apartamentos}',
  'AssignApartmentsController@storeFromIdentity');
Route::get('/habitantes-remover/{usuarios}/{apartamentos}',
  'AssignApartmentsController@removeFromIdentity');

Route::controllers([
  'auth' => 'Auth\AuthController',
  'password' => 'Auth\PasswordController',
]);

app/Building.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Building extends Model {

  protected $table = 'buildings';

  protected $dates = ['deleted_at'];

  protected $fillable = [
    'user_id',
    'direction_id',
    'name',
    'total_floors',
    'created_by',
    'updated_by'
  ];

  /**
   * regresa los eventos paginados
   * @return object LengthAwarePaginator
   */
  public function getEventosPaginadosAttribute()
  {
    return $this->eventos()->paginate(5);
  }

  /**
   * regresa los eventos paginados
   * @return object LengthAwarePaginator
   */
  public function getMensajesPaginadosAttribute()
  {
    return $this->mensajes()->paginate(5);
  }

  /**
   * regresa los ultimos 3 eventos relacionados con el edificio
   */
  public function getUltimosEventosAttribute()
  {
    return $this->eventos()->orderBy('updated_at', 'desc')->take(3)->get();
  }

  /**
   * regresa los ultimos 3 movimientos relacionados con el edificio
   */
  public function getUltimosMovimientosAttribute()
  {
    return $this->movimientos()->orderBy('updated_at', 'desc')->take(3)->get();
  }

  /**
   * relacion 1aN
   */
  public function encargado(){
    return $this->belongsTo('App\User', 'user_id');
  }

  /**
   * relacion 1aN
   */
  public function direccion(){
    return $this->belongsTo('App\Direction', 'direction_id');
  }

  /**
   * la relacion entre apartamentos y edificios
   * donde UN apartamento tiene UN edificio y
   * en UN edificio pueden haber VARIOS
   * apartamentos.
   */
  public function apartamentos(){
    return $this->hasMany('App\Apartment');
  }

  /**
   * la relacion entre eventos y edificios
   * donde UN evento tiene UN edificio y
   * en UN edificio pueden haber VARIOS
   * eventos.
   */
  public function eventos(){
    return $this->hasMany('App\Event');
  }

  /**
   * la relacion entre eventos y edificios
   * donde UN evento tiene UN edificio y
   * en UN edificio pueden haber VARIOS
   * eventos.
   */
  public function mensajes(){
    return $this->hasMany('App\Message');
  }

  /**
   * la relacion entre items y edificios
   * donde UN item tiene UN edificio y
   * en UN edificio pueden haber VARIOS
   * items.
   */
  public function items(){
    return $this->hasMany('App\Item');
  }

  /**
   * la relacion entre miembros de la gestiones multifamiliares y edificios
   * donde UN miembros de la gestion multifamiliar tiene VARIOS
   * edificios y en UN edificio pueden haber VARIOS
   * miembros de la gestiones multifamiliares.
   */
  public function miembrosDeGestion(){
    return $this->belongsToMany('App\User');
  }

  /**
   * la relacion entre movimientos y edificios
   * donde UN movimiento tiene UN edificio y
   * en UN edificio pueden haber VARIOS
   * movimientos.
   */
  public function movimientos(){
    return $this->hasMany('App\Movement');
  }

}

app/Http/Controllers/BuildingsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\BuildingRequest;
use App\Http\Controllers\Controller;
use Session;
use Auth;
use App\Building;
use App\Apartment;
use App\User;
use App\Profile;

use Illuminate\Http\Request;

class BuildingsController extends Controller {

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
    $this->middleware('administrador.evento',
      ['except' => ['index', 'show', 'floors', 'events', 'gestions']
    ]);
  }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    // hacer resource o algo para validar como en eventscontroller
    $edificios = Building::all();
    $usuario = Auth::user()->apartamentos;
    return view('buildings.index', compact('edificios', 'usuario'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    $edificio = new Building;

    $administradores = Profile::where('description', 'Administrador')->get();

    return view('buildings.create', compact('edificio', 'administradores'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @return Response
   */
  public function store(BuildingRequest $request)
  {
    $direccion = new \App\Direction($request->all());
    $direccion->created_by = Auth::user()->id;
    $direccion->updated_by = Auth::user()->id;
    $direccion->save();
    $edificio = new Building($request->all());
    $edificio->created_by = Auth::user()->id;
    $edificio->updated_by = Auth::user()->id;
    $direccion->edificios()->save($edificio);
    // mensaje de exito
    flash('El Edificio se ha creado con exito.');
    return redirect()->action('BuildingsController@show', $edificio->id);
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $edificio = Building::findOrFail($id);

    return view('buildings.show', compact('edificio'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $edificio = Building::findOrFail($id);

    $administradores = Profile::where('description', 'Administrador')->get();

    return view('buildings.edit', compact('edificio', 'administradores'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function update($id, BuildingRequest $request)
  {
    // se busca el edificio solicitado o falla
    $edificio = Building::findOrFail($id);
    $edificio->updated_by = Auth::user()->id;
    // dd($request->all());
    // se guarda la informacion del edificio
    $edificio->update($request->all());
    // se guarda la direccion por el edifico
    // para tener el id de direccion
    // (edificio->direction_id)
    $edificio->direccion()->update($request->all());
    // mensaje de exito
    flash('El Edificio ha sido actualizado con exito.');
    return redirect()->action('IndexController@index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    //
  }

  /**
   * Muestra los items relacionados con
   * algun edificio en el sistema
   */
  public function items($id)
  {
    $edificio = Building::findOrFail($id);
    return view('items.showByBuilding', compact('edificio'));
  }

  /**
   * Muestra los eventos relacionados con
   * algun edificio en el sistema
   */
  public function events($id)
  {
    $edificio = Building::findOrFail($id);
    return view('events.showByBuilding', compact('edificio'));
  }

  /**
   * Muestra los messages relacionados con
   * algun edificio en el sistema
   */
  public function messages($id)
  {
    $edificio = Building::findOrFail($id);
    return view('messages.showByBuilding', compact('edificio'));
  }

  /**
   * Muestra la gestion multifamiliar relacionada
   * con algun edificio en el sistema
   */
  public function gestions($id)
  {
    $edificio = Building::findOrFail($id);
    return view('gestions.showByBuilding', compact('edificio'));
  }

  /**
   * crear gestion multifamiliar relacionada
   * con algun edificio en el sistema
   */
  public function gestionsCreate($id)
  {
    $edificio = Building::findOrFail($id);
    $usuario = new \App\User;
    return view('gestions.create', compact('edificio', 'usuario'));
  }

  /**
   * Muestra la gestion multifamiliar relacionada
   * con algun edificio en el sistema
   */
  public function movements($id)
  {
    $edificio = Building::findOrFail($id);
    return view('movements.showByBuilding', compact('edificio'));
  }

  /**
   * crear gestion multifamiliar relacionada
   * con algun edificio en el sistema
   */
  public function movementsCreate($id)
  {
    // el edifico
    $edificio = Building::findOrFail($id);

    // el movimiento
    $movimiento = new \App\Movement;

    // por cada miembro de la gestion multifamiliar
    // se sacan las cuentas segun su responsable
    foreach ($edificio->miembrosDeGestion as $usuario) :
      $cuentas[] = \App\Account::where('user_id', $usuario->id)->get();
    endforeach;

    // todos los tipos de movimientos
    $tipos = \App\MovementType::all();

    // los items segun el id del edificio
    // para anclar concepto a un item
    $items = \App\Item::where('building_id', $id)->get();

    // la vista con todas las variables
    return view(
      'movements.create', compact(
        'edificio',
        'movimiento',
        'cuentas',
        'items',
        'tipos'
      ));
  }
  /**
  * --------------------------------------------------
  * --------------------------------------------------
  * --------------------------------------------------
  * ----------------------APIs------------------------
  * --------------------------------------------------
  * --------------------------------------------------
  * --------------------------------------------------
  */


  /**
  * Devuelve los pisos existentes en algun edificio
  * para poder ser usado por el ajax
  * dentro del formulario
  * de apartamentos
  *
  * @param $id integer el id del edificio
  */
  public function floors($id)
  {
    $edificio = Building::findOrFail($id);
    return $edificio->total_floors;
  }

  /**
  * Devuelve los Apartamentos existentes en algun edificio
  * para poder ser usado por el ajax
  * dentro del formulario
  * de asignar apartamentos
  *
  * @param $id integer el id del edificio
  */
  public function apartments($id)
  {
    $edificio = Building::findOrFail($id);
    return $edificio->apartamentos()->get()->count();
  }


}

resources/views/buildings/_form.blade.php
<div class="form-group">
  {!! Form::label('name', 'Nombre:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('user_id', 'Encargado:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    <select name="user_id" class="form-control">
    @foreach ($administradores as $administrador)
      @if ($edificio->user_id === $administrador->usuarios->first()->id)
        <option value="{{ $administrador->id }}" selected="selected">
      @else
        <option value="{{ $administrador->id }}">
      @endif
        {{$administrador->usuarios->first()->first_name}}
        {{$administrador->usuarios->first()->first_surname}}
        {{$administrador->usuarios->first()->email}}
      </option>
    @endforeach
  </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('total_floors', 'Pisos:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    {!! Form::input('number', 'total_floors', $edificio->total_floors, ['class' => 'form-control', 'min' => '0', 'max' => '200']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('exact_direction', 'Direccion:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    {!! Form::text('exact_direction',
    $edificio->direccion->exact_direction,
    ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('state_id', 'Estado:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="state_id" id="state_id" class="form-control">
    </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('town_id', 'Municipio:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="town_id" id="town_id" class="form-control">
    </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('parish_id', 'Parroquia:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="parish_id" id="parish_id" class="form-control">
      <option value="{!! $edificio->direccion->parish_id !!}"></option>
    </select>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    {!! Form::submit($textoBotonSubmit, ['class' => 'form-control btn btn-primary']) !!}
  </div>
</div>

resources/views/buildings/_formCreate.blade.php
<div class="form-group">
  {!! Form::label('name', 'Nombre:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
  </div>
  {!! Form::label('user_id', 'Encargado:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-4">
    <select name="user_id" class="form-control">
    @foreach ($administradores as $administrador)
      <option value="{{ $administrador->id }}">
        {{$administrador->usuarios->first()->first_name}}
        {{$administrador->usuarios->first()->first_surname}}
        {{$administrador->usuarios->first()->email}}
      </option>
    @endforeach
  </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('total_floors', 'Pisos:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    {!! Form::input('number', 'total_floors', null, ['class' => 'form-control', 'min' => '0', 'max' => '200']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('exact_direction', 'Direccion:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    {!! Form::text('exact_direction', null, ['class' => 'form-control']) !!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('state_id', 'Estado:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="state_id" id="state_id" class="form-control">
    </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('town_id', 'Municipio:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="town_id" id="town_id" class="form-control">
    </select>
  </div>
</div>

<div class="form-group">
  {!! Form::label('parish_id', 'Parroquia:', ['class' => 'col-md-2 control-label']) !!}
  <div class="col-md-10">
    <select name="parish_id" id="parish_id" class="form-control">
    </select>
  </div>
</div>

<div class="form-group">
  <div class="col-md-12">
    {!! Form::submit($textoBotonSubmit, ['class' => 'form-control btn btn-primary']) !!}
  </div>
</div>

resources/views/buildings/create.blade.php
@extends('master')

@section('title')
  - Crear - Eventos
@stop

@section('contenido')
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">Crea un nuevo Evento en el sistemaCONDOR</div>
          <div class="panel-body">
            @include('errors.lista')
            {!! Form::open(['action' => 'BuildingsController@store', 'class' => 'form-horizontal']) !!}
              @include('buildings._formCreate', ['textoBotonSubmit' => 'Añadir nuevo Edificio'])
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@stop

@section('js')
  <!-- ajax de edo/mun/par -->
  <script src="{!! asset('js/ajax/getDirecciones.js') !!}"></script>
@stop

resources/views/buildings/edit.blade.php
@extends('master')

@section('title')
  - Actualizar - Edificios - {{ $edificio->name }}
@stop

@section('contenido')
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">Editar {{ $edificio->name }}</div>
          <div class="panel-body">
            @include('errors.lista')
            {!! Form::model($edificio, [
                'method' => 'PATCH',
                'action' => ['BuildingsController@update', $edificio->id],
                'class'  => 'form-horizontal'
                ]) !!}
              @include('buildings._form', ['textoBotonSubmit' => 'Actualizar Edificio'])
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@stop

@section('js')
  <!-- ajax de edo/mun/par -->
  <script src="{!! asset('js/ajax/setDirecciones.js') !!}"></script>
@stop

resources/views/buildings/index.blade.php
@extends('master')

@section('title')
  - Index - Edificios
@stop

@section('contenido')
  <div class="container">
    @unless (!isset($edificios))
      @foreach ($edificios as $edificio)
        <h1>Edificio
          {!! link_to_action('BuildingsController@show',
            $edificio->name, $edificio->id) !!}
        </h1>
        <p>
          {{ $edificio->direccion->exact_direction }}.
        </p>
        <p>
          Encargado:
          <i>
            {!! link_to_action(
                  'UsersController@show',
                  $edificio->encargado->first_name.
                  ', '.
                  $edificio->encargado->first_surname,
                  $edificio->encargado->id
                ) !!}
            Email: {!! Html::mailto($edificio->encargado->email) !!}
          </i>
        </p>
      @endforeach
    @endunless
  </div>
@stop

resources/views/buildings/show.blade.php
@extends('master')

@section('title')
  - Edificios - {{ $edificio->name }}
@stop

@section('contenido')
  <div class="container">
    <h1>
      Edificio
      @if (Auth::user()->id === $edificio->encargado->id)
        <a href="{{ action('BuildingsController@edit', $edificio->id) }}">
          {{ $edificio->name }}
        </a>
      @else
        <a href="{{ action('BuildingsController@show', $edificio->id) }}">
          {{ $edificio->name }}
        </a>
      @endif
    </h1>
    {!! link_to_action('BuildingsController@gestions',
      'Miembros de Gestion Multifamiliar',
      $edificio->id,
      ['class' => 'btn btn-default']
    ) !!}
    @if (Auth::user()->perfil->description === 'Administrador')
      {!! link_to_action('BuildingsController@messages',
        'Mensajes',
        $edificio->id,
        ['class' => 'btn btn-default']
      ) !!}
      {!! link_to_action('BuildingsController@movements',
        'Movimientos',
        $edificio->id,
        ['class' => 'btn btn-default']
      ) !!}
      {!! link_to_action('BuildingsController@items',
        'Inventario',
        $edificio->id,
        ['class' => 'btn btn-default']
      ) !!}
    @endif
    {!! link_to_action('BuildingsController@events',
      'Eventos',
      $edificio->id,
      ['class' => 'btn btn-default']
    ) !!}
    <div id="apartamentos">
      <div id="apartamentos-lista">
        <h2>
          Apartamentos existentes
        </h2>
        @if ($edificio->apartamentos->isEmpty())
          {!! link_to_action('ApartmentsController@create', 'Crear Nuevo Apartamento', null, ['class' => 'btn btn-primary']) !!}
          {!! link_to_action('ApartmentsController@createMultiple', 'Crear varios Apartamentos', $edificio->id, ['class' => 'btn btn-info']) !!}
        @endif
        @foreach ($edificio->apartamentos as $apartamento)
          <section>
            <p>
              {!! link_to_action('ApartmentsController@show',
                'Numero '.$apartamento->number,
                $apartamento->id
              ) !!}
              <small>
                @unless ( $apartamento->propietario()->get()->isEmpty() )
                  Propietario:
                  {!! link_to_action('UsersController@show',
                    $apartamento->propietario->first_name.
                    ', '.
                    $apartamento->propietario->first_surname,
                    $apartamento->propietario->id
                  ) !!}
                  <br>
                  <strong>
                    Telf: {{ $apartamento->propietario->phone }}
                  </strong> -
                  Email: {!! Html::mailto($apartamento->propietario->email) !!}.
                @else
                  <i>Sin Propietario.</i>
                @endunless
                <span>Habitantes: {{ $apartamento->habitantes->count() }}</span>
              </small>
            </p>
          </section>
        @endforeach
      </div>
      <div class="col-sm-6">
        <div class="row">
          <h2>
            {!! link_to_action('BuildingsController@movements',
              'Ultimos Movimientos',
              $edificio->id
            ) !!}
          </h2>
          @foreach ($edificio->ultimos_movimientos as $movimiento)
            <article>
              <header>
                <h3>
                  {!! $movimiento->concept !!}
                </h3>
              </header>
              <section>
                <p class="body">
                  @unless ($movimiento->cuenta()->get()->isEmpty())
                    Cuenta N°: {{ $movimiento->cuenta->bank_number }}
                  @endunless
                </p>
              </section>
              <section>
                <p>
                  @unless ($movimiento->tipo()->get()->isEmpty())
                    @if ($movimiento->tipo->description === 'Entrada')
                      <span class="mediano verde">
                        <i>
                          {{ $movimiento->tipo->description }}
                        </i>
                        <strong class="parse_numero">{{ $movimiento->operation }}</strong>
                      </span>
                    @elseif ($movimiento->tipo->description === 'Salida')
                      <span class="mediano rojo">
                        <i>
                          {{ $movimiento->tipo->description }}
                        </i>
                        <strong class="parse_numero">{{ $movimiento->operation }}</strong>
                      </span>
                    @else
                      <span class="mediano amarillo">
                        <i>
                          {{ $movimiento->tipo->description }}
                        </i>
                        <strong class="parse_numero">{{ $movimiento->operation }}</strong>
                      </span>
                    @endif
                  @endunless
                </p>
              </section>
              <section>
                <p>
                  <strong>
                    @if($movimiento->check_number)
                      Cheque N°: {{ $movimiento->check_number }}
                    @endif
                    {{ $movimiento->responsable->first_name }}
                    {{ $movimiento->responsable->first_surname }}
                  </strong>
                  {!! Html::mailto($movimiento->responsable->email) !!}
                </p>
              </section>
              <footer>
                <p>
                  <i>
                    Ultima actualizacion
                    {!! Date::parse($movimiento->updated_at)->diffForHumans(); !!}.
                  </i>
                </p>
              </footer>
            </article>
          @endforeach
        </div>
        <hr/>
        <div class="row">
          <h2>
            {!! link_to_action('BuildingsController@events',
              'Ultimos Eventos',
              $edificio->id
            ) !!}
          </h2>
          @foreach ($edificio->ultimos_eventos as $evento)
            <article>
              <header>
                <h3>
                  {!! link_to_action('EventsController@show', $evento->title, $evento->id) !!}
                </h3>
              </header>
              <p class="body">
                {{ $evento->body }}
              </p>
              <footer>
                <p>
                  <strong>
                    {!! $evento->tipo->description !!}.
                  </strong>
                  <i>
                    Ultima actualizacion
                    {!! Date::parse($evento->updated_at)->diffForHumans(); !!}.
                  </i>
                </p>
              </footer>
            </article>
          @endforeach
        </div>
      </div>
    </div>
  </div>
@stop

@section('js')
  <script src="{!! asset('vendor/js/numeraljs/numeral.js') !!}"></script>
  <script src="{!! asset('vendor/js/numeraljs/languages.js') !!}"></script>
  <script src="{!! asset('js/movimientos/operacion.js') !!}"></script>
@stop